### ISSUE TITLE
Failed to parse

### ISSUE THREAD

**Issue by greatjack1** [MarkusLewis/Podcast-Feed-Library#11]
I am trying to parse the following rss feed, and I am getting a exception.

Here is the feed, is their any reason why it is not working?
view-source:https://www.omnycontent.com/d/playlist/a7b0bd27-d748-4fbe-ab3b-a6fa0049bcf6/aaf310db-97a4-428f-bde6-a84e0041aabe/2247fc58-f667-4d2a-a67f-a84e0041c550/podcast.rss

**Comment by MarkusLewis** [comment]
Hi Yaakov, what exception is being thrown?
