### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by jsgrosman** [MarkusLewis/Podcast-Feed-Library#14]
We're currently using the 2.2 release, but running into the multithreading issues with SimpleDateFormat that you've fixed in the latest commits.

It's worked very well, other than that.

Can you create a 2.3 release JAR of the latest code?

Thanks

**Comment by MarkusLewis** [comment]
Hi Jason,

Thanks for getting in touch. I'll push out a new build this weekend

**Comment by MarkusLewis** [comment]
Hi Jason,

That's version 2.3 pushed out now. Let me know if you run into any further issues.

**Comment by jsgrosman** [comment]
Thank you!
