### ISSUE TITLE
Repository is down

### ISSUE THREAD

**Issue by LinusCDE** [MarkusLewis/Podcast-Feed-Library#17]
Hi, sadly the repository went down. Can you do something about it?

Regards,
Linus

**Comment by LinusCDE** [comment]
For a temporary fix, I [forked the repo](https://github.com/LinusCDE/Podcast-Feed-Library), built it (one test was remove due to problems) and published it to my own repository.

For anyone who also has problems, can use my repository at https://maven.cosmos-ink.net/ instead of https://maven.icosillion.com/artifactory/open-source/ . I plan on keeping this up as long as possible but can't make promises.

**Comment by MarkusLewis** [comment]
Hi Linus,

Sorry about this. An expired TLS certificate knocked the package host offline. I've popped in a temporary fix and I'll be moving it to something more resilient this afternoon.

**Comment by LinusCDE** [comment]
Sounds cool. For hosting this you don't really need anything fancy.  
My setup is using rclone's webdav serve feature behind an nginx server.
Only drawback is, that rclone doesn't create the directory maven tries to publish too. That has to be created by hand when the error occurs.
