### ISSUE TITLE
Android Studio Compatibility

### ISSUE THREAD

**Issue by oddalot** [MarkusLewis/Podcast-Feed-Library#6]
I got this to work as a dependency in Android Studio, but I had to do the following:

compile ('com.icosillion.podengine:podengine:2.1') {
        exclude group: 'xml-apis'
}

Maybe it's just a problem with my setup, I'm not sure.

I'm not exactly sure what the problem is, but the error I was getting is the following: Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: Unable to pre-dex '/home/oddalot/.gradle/caches/modules-2/files-2.1/xml-apis/xml-apis/1.0.b2/3136ca936f64c9d68529f048c2618bd356bf85c9/xml-apis-1.0.b2.jar' to '/home/oddalot/AndroidStudioProjects/Podtastic/app/build/intermediates/pre-dexed/debug/xml-apis-1.0.b2_4e16f10e0045765a8c3405fa03d74170faf048ba.jar'

**Comment by 410063005** [comment]
I got the same problem.  Another solution can be found in this post  https://stackoverflow.com/questions/25156506/trouble-processing-javax-xml-parsers-documentbuilder-class-ill-advised-or-mis

**Comment by MarkusLewis** [comment]
Hi oddalot,

Thanks for bringing this to my attention. I've updated the DOM4J dependency which was causing the issue to 2.0.2 which should work correctly with Android Studio. I've tested this change with the latest version of Android Studio and it seems to be working. Could you check if this fixes the issue for you by using `com.icosillion.podengine:podengine:2.2-SNAPSHOT` in your Gradle file? If it does I'll push a new build up with the changes.

**Comment by oddalot** [comment]
Seems to work!

**Comment by MarkusLewis** [comment]
I've published 2.2 now which should solve this 🙂 Thanks for your help!
